#Input image
IMG_W = int(768)
IMG_H = int(576)
IMG_C = int(3)
NEW_W = int(416)
NEW_H = int(((IMG_H*NEW_W)/IMG_W))      # 312
IMAGE_INPUT = int(IMG_W*IMG_H*IMG_C) 
EXTRA_H = int(((NEW_W-NEW_H)/2))        # 52

#Input network
NTW_IN_W = int(416)
NTW_IN_C = int(3)
NTW_IN_NUM_KER = int(16)
NTW_IN_KER_SIZE = int(3)
NTW_IN_PAD = int(1)
NTW_IN_BATCH_NORM = int(1)
NTW_IN_NEXT_PADD = int(0)
NTW_IN_NEXT_STRIDE = int(0)
NTW_IN_IGNORE_PADD = int(0)
NETWORK_INPUT = int(((NTW_IN_W+2*NTW_IN_PAD)*(NTW_IN_W+2*NTW_IN_PAD)*NTW_IN_C))*2

#Layer1 (conv)
DATA_LAYER_1 = int(((NTW_IN_W+NTW_IN_NEXT_STRIDE+2*NTW_IN_NEXT_PADD)*(NTW_IN_W+NTW_IN_NEXT_STRIDE+2*NTW_IN_NEXT_PADD)*NTW_IN_NUM_KER))*2
#WEIGHTS_LAYER_1 = int((NTW_IN_NUM_KER*(1+NTW_IN_BATCH_NORM)+NTW_IN_NUM_KER*NTW_IN_KER_SIZE*NTW_IN_KER_SIZE*NTW_IN_C))

#Layer2 (maxpool)
LAYER_2_W = int(NTW_IN_W)
LAYER_2_NUM_KER = int(NTW_IN_NUM_KER)
LAYER_2_DOWNSAMPLE = int(1)
LAYER_2_IGNORE_PADD = int(0)
DATA_LAYER_2 = int(((LAYER_2_W/(1+LAYER_2_DOWNSAMPLE)+2)*(LAYER_2_W/(1+LAYER_2_DOWNSAMPLE)+2)*LAYER_2_NUM_KER))*2

#Layer3 (conv)
LAYER_3_W = int((LAYER_2_W/2))
LAYER_3_C = int(LAYER_2_NUM_KER)
LAYER_3_NUM_KER = int(LAYER_3_C*2)
LAYER_3_KER_SIZE = int(3)
LAYER_3_PAD = int(1)
LAYER_3_BATCH_NORM = int(1)
LAYER_3_NEXT_PADD = int(0)
LAYER_3_NEXT_STRIDE = int(0)
LAYER_3_IGNORE_PADD = int(0)
DATA_LAYER_3 = int(((LAYER_3_W+LAYER_3_NEXT_STRIDE+2*LAYER_3_NEXT_PADD)*(LAYER_3_W+LAYER_3_NEXT_STRIDE+2*LAYER_3_NEXT_PADD)*LAYER_3_NUM_KER))*2
#WEIGHTS_LAYER_3 = int((LAYER_3_NUM_KER*(1+LAYER_3_BATCH_NORM)+LAYER_3_NUM_KER*LAYER_3_KER_SIZE*LAYER_3_KER_SIZE*LAYER_3_C))

#Layer4 (maxpool)
LAYER_4_W = int(LAYER_3_W)
LAYER_4_NUM_KER = int(LAYER_3_NUM_KER)
LAYER_4_DOWNSAMPLE = int(1)
LAYER_4_IGNORE_PADD = int(0)
DATA_LAYER_4 = int(((LAYER_3_W/(1+LAYER_4_DOWNSAMPLE)+2)*(LAYER_3_W/(1+LAYER_4_DOWNSAMPLE)+2)*LAYER_3_NUM_KER))*2

#Layer5 (conv)
LAYER_5_W = int((LAYER_4_W/2))
LAYER_5_C = int(LAYER_4_NUM_KER)
LAYER_5_NUM_KER = int(LAYER_5_C*2)
LAYER_5_KER_SIZE = int(3)
LAYER_5_PAD = int(1)
LAYER_5_BATCH_NORM = int(1)
LAYER_5_NEXT_PADD = int(0)
LAYER_5_NEXT_STRIDE = int(0)
LAYER_5_IGNORE_PADD = int(0)
DATA_LAYER_5 = int(((LAYER_5_W+LAYER_5_NEXT_STRIDE+2*LAYER_5_NEXT_PADD)*(LAYER_5_W+LAYER_5_NEXT_STRIDE+2*LAYER_5_NEXT_PADD)*LAYER_5_NUM_KER))*2
#WEIGHTS_LAYER_5 = int((LAYER_5_NUM_KER*(1+LAYER_5_BATCH_NORM)+LAYER_5_NUM_KER*LAYER_5_KER_SIZE*LAYER_5_KER_SIZE*LAYER_5_C))

#Layer6 (maxpool)
LAYER_6_W = int(LAYER_5_W)
LAYER_6_NUM_KER = int(LAYER_5_NUM_KER)
LAYER_6_DOWNSAMPLE = int(1)
LAYER_6_IGNORE_PADD = int(0)
DATA_LAYER_6 = int(((LAYER_5_W/2+(1+LAYER_6_DOWNSAMPLE))*(LAYER_5_W/(1+LAYER_6_DOWNSAMPLE)+2)*LAYER_5_NUM_KER))*2

#Layer7 (conv)
LAYER_7_W = int((LAYER_6_W/2))
LAYER_7_C = int(LAYER_6_NUM_KER)
LAYER_7_NUM_KER = int(LAYER_7_C*2)
LAYER_7_KER_SIZE = int(3)
LAYER_7_PAD = int(1)
LAYER_7_BATCH_NORM = int(1)
LAYER_7_NEXT_PADD = int(0)
LAYER_7_NEXT_STRIDE = int(0)
LAYER_7_IGNORE_PADD = int(0)
DATA_LAYER_7 = int(((LAYER_7_W+LAYER_7_NEXT_STRIDE+2*LAYER_7_NEXT_PADD)*(LAYER_7_W+LAYER_7_NEXT_STRIDE+2*LAYER_7_NEXT_PADD)*LAYER_7_NUM_KER))*2
#WEIGHTS_LAYER_7 = int((LAYER_7_NUM_KER*(1+LAYER_7_BATCH_NORM)+LAYER_7_NUM_KER*LAYER_7_KER_SIZE*LAYER_7_KER_SIZE*LAYER_7_C))

#Layer8 (maxpool)
LAYER_8_W = int(LAYER_7_W)
LAYER_8_NUM_KER = int(LAYER_7_NUM_KER)
LAYER_8_DOWNSAMPLE = int(1)
LAYER_8_IGNORE_PADD = int(0)
DATA_LAYER_8 = int(((LAYER_7_W/(1+LAYER_8_DOWNSAMPLE)+2)*(LAYER_7_W/(1+LAYER_8_DOWNSAMPLE)+2)*LAYER_7_NUM_KER))*2

#Layer9 (conv)
LAYER_9_W = int((LAYER_8_W/2))
LAYER_9_C = int(LAYER_8_NUM_KER)
LAYER_9_NUM_KER = int(LAYER_9_C*2)
LAYER_9_KER_SIZE = int(3)
LAYER_9_PAD = int(1)
LAYER_9_BATCH_NORM = int(1)
LAYER_9_NEXT_PADD = int(1)
LAYER_9_NEXT_STRIDE = int(0)
LAYER_9_IGNORE_PADD = int(0)
DATA_LAYER_9 = int(((LAYER_9_W+LAYER_9_NEXT_STRIDE+2*LAYER_9_NEXT_PADD)*(LAYER_9_W+LAYER_9_NEXT_STRIDE+2*LAYER_9_NEXT_PADD)*LAYER_9_NUM_KER))*2
#WEIGHTS_LAYER_9 = int((LAYER_9_NUM_KER*(1+LAYER_9_BATCH_NORM)+LAYER_9_NUM_KER*LAYER_9_KER_SIZE*LAYER_9_KER_SIZE*LAYER_9_C))

#Layer10 (maxpool)
LAYER_10_W = int(LAYER_9_W)
LAYER_10_NUM_KER = int(LAYER_9_NUM_KER)
LAYER_10_DOWNSAMPLE = int(1)
LAYER_10_IGNORE_PADD = int(1)
DATA_LAYER_10 = int(((LAYER_9_W/(1+LAYER_10_DOWNSAMPLE)+2)*(LAYER_9_W/(1+LAYER_10_DOWNSAMPLE)+2)*LAYER_9_NUM_KER))*2

#Layer11 (conv)
LAYER_11_W = int((LAYER_10_W/2))
LAYER_11_C = int(LAYER_10_NUM_KER)
LAYER_11_NUM_KER = int(LAYER_11_C*2)
LAYER_11_KER_SIZE = int(3)
LAYER_11_PAD = int(1)
LAYER_11_BATCH_NORM = int(1)
LAYER_11_NEXT_PADD = int(0)
LAYER_11_NEXT_STRIDE = int(1)
LAYER_11_IGNORE_PADD = int(0)
DATA_LAYER_11 = int(((LAYER_11_W+LAYER_11_NEXT_STRIDE+2*LAYER_11_NEXT_PADD)*(LAYER_11_W+LAYER_11_NEXT_STRIDE+2*LAYER_11_NEXT_PADD)*LAYER_11_NUM_KER))*2
#WEIGHTS_LAYER_11 = int((LAYER_11_NUM_KER*(1+LAYER_11_BATCH_NORM)+LAYER_11_NUM_KER*LAYER_11_KER_SIZE*LAYER_11_KER_SIZE*LAYER_11_C))

#Layer12 (maxpool)
LAYER_12_W = int(LAYER_11_W)
LAYER_12_NUM_KER = int(LAYER_11_NUM_KER)
LAYER_12_DOWNSAMPLE = int(0)
LAYER_12_IGNORE_PADD = int(0)
DATA_LAYER_12 = int(((LAYER_11_W/(1+LAYER_12_DOWNSAMPLE)+2)*(LAYER_11_W/(1+LAYER_12_DOWNSAMPLE)+2)*LAYER_11_NUM_KER))*2

#Layer13 (conv)
LAYER_13_W = int(LAYER_12_W)
LAYER_13_C = int(LAYER_12_NUM_KER)
LAYER_13_NUM_KER = int(LAYER_13_C*2)
LAYER_13_KER_SIZE = int(3)
LAYER_13_PAD = int(1)
LAYER_13_BATCH_NORM = int(1)
LAYER_13_NEXT_PADD = int(0)
LAYER_13_NEXT_STRIDE = int(0)
LAYER_13_IGNORE_PADD = int(0)
DATA_LAYER_13 = int(((LAYER_13_W+LAYER_13_NEXT_STRIDE+2*LAYER_13_NEXT_PADD)*(LAYER_13_W+LAYER_13_NEXT_STRIDE+2*LAYER_13_NEXT_PADD)*LAYER_13_NUM_KER))*2
#WEIGHTS_LAYER_13 = int((LAYER_13_NUM_KER*(1+LAYER_13_BATCH_NORM)+LAYER_13_NUM_KER*LAYER_13_KER_SIZE*LAYER_13_KER_SIZE*LAYER_13_C))

#Layer14 (conv)
LAYER_14_W = int(LAYER_13_W)
LAYER_14_C = int(LAYER_13_NUM_KER)
LAYER_14_NUM_KER = int((LAYER_14_C/4))
LAYER_14_KER_SIZE = int(1)
LAYER_14_PAD = int(0)
LAYER_14_BATCH_NORM = int(1)
LAYER_14_NEXT_PADD = int(1)
LAYER_14_NEXT_STRIDE = int(0)
LAYER_14_IGNORE_PADD = int(0)
DATA_LAYER_14 = int(((LAYER_14_W+LAYER_14_NEXT_STRIDE+2*LAYER_14_NEXT_PADD)*(LAYER_14_W+LAYER_14_NEXT_STRIDE+2*LAYER_14_NEXT_PADD)*LAYER_14_NUM_KER))*2
#WEIGHTS_LAYER_14 = int((LAYER_14_NUM_KER*(1+LAYER_14_BATCH_NORM)+LAYER_14_NUM_KER*LAYER_14_KER_SIZE*LAYER_14_KER_SIZE*LAYER_14_C))

#Layer15 (conv)
LAYER_15_W = int(LAYER_14_W)
LAYER_15_C = int(LAYER_14_NUM_KER)
LAYER_15_NUM_KER = int((LAYER_15_C*2))
LAYER_15_KER_SIZE = int(3)
LAYER_15_PAD = int(1)
LAYER_15_BATCH_NORM = int(1)
LAYER_15_NEXT_PADD = int(0)
LAYER_15_NEXT_STRIDE = int(0)
LAYER_15_IGNORE_PADD = int(0)
DATA_LAYER_15 = int(((LAYER_15_W+LAYER_15_NEXT_STRIDE+2*LAYER_15_NEXT_PADD)*(LAYER_15_W+LAYER_15_NEXT_STRIDE+2*LAYER_15_NEXT_PADD)*LAYER_15_NUM_KER))*2
#WEIGHTS_LAYER_15 = int((LAYER_15_NUM_KER*(1+LAYER_15_BATCH_NORM)+LAYER_15_NUM_KER*LAYER_15_KER_SIZE*LAYER_15_KER_SIZE*LAYER_15_C))

#Layer16 (conv)
LAYER_16_W = int(LAYER_15_W)
LAYER_16_C = int(LAYER_15_NUM_KER)
LAYER_16_NUM_KER = int(255)
LAYER_16_KER_SIZE = int(1)
LAYER_16_PAD = int(0)
LAYER_16_BATCH_NORM = int(0)
LAYER_16_NEXT_PADD = int(0)
LAYER_16_NEXT_STRIDE = int(0)
LAYER_16_IGNORE_PADD = int(0)
DATA_LAYER_16 = int(((LAYER_16_W+LAYER_16_NEXT_STRIDE+2*LAYER_16_NEXT_PADD)*(LAYER_16_W+LAYER_16_NEXT_STRIDE+2*LAYER_16_NEXT_PADD)*LAYER_16_NUM_KER))*2
#WEIGHTS_LAYER_16 = int((LAYER_16_NUM_KER*(1+LAYER_16_BATCH_NORM)+LAYER_16_NUM_KER*LAYER_16_KER_SIZE*LAYER_16_KER_SIZE*LAYER_16_C))

#Layer 17 (yolo)
LAYER_17_W = int(LAYER_16_W)
DATA_LAYER_17 = int((LAYER_17_W*LAYER_17_W*255))*2

#Layer19 (conv)
LAYER_19_W = int(LAYER_14_W)
LAYER_19_C = int(LAYER_14_NUM_KER)
LAYER_19_NUM_KER = int((LAYER_19_C/2))
LAYER_19_KER_SIZE = int(1)
LAYER_19_PAD = int(1)
LAYER_19_BATCH_NORM = int(1)
LAYER_19_NEXT_PADD = int(0)
LAYER_19_NEXT_STRIDE = int(0)
LAYER_19_IGNORE_PADD = int(1)
DATA_LAYER_19 = int(((LAYER_19_W+LAYER_19_NEXT_STRIDE+2*LAYER_19_NEXT_PADD)*(LAYER_19_W+LAYER_19_NEXT_STRIDE+2*LAYER_19_NEXT_PADD)*LAYER_19_NUM_KER))*2
#WEIGHTS_LAYER_19 = int((LAYER_19_NUM_KER*(1+LAYER_19_BATCH_NORM)+LAYER_19_NUM_KER*LAYER_19_KER_SIZE*LAYER_19_KER_SIZE*LAYER_19_C))

#Layer20 (upsample)
LAYER_20_W = int(LAYER_19_W)
LAYER_20_NUM_KER = int(LAYER_19_NUM_KER)
DATA_LAYER_20 = int(((LAYER_20_W*2+2)*(LAYER_20_W*2+2)*LAYER_20_NUM_KER))*2

#Layer22 (conv)
LAYER_22_W = int(LAYER_20_W*2)
LAYER_22_C = int((LAYER_20_NUM_KER + LAYER_9_NUM_KER))
LAYER_22_NUM_KER = int(LAYER_9_NUM_KER)
LAYER_22_KER_SIZE = int(3)
LAYER_22_PAD = int(1)
LAYER_22_BATCH_NORM = int(1)
LAYER_22_NEXT_PADD = int(0)
LAYER_22_NEXT_STRIDE = int(0)
LAYER_22_IGNORE_PADD = int(0)
DATA_LAYER_22 = int(((LAYER_22_W+LAYER_22_NEXT_STRIDE+2*LAYER_22_NEXT_PADD)*(LAYER_22_W+LAYER_22_NEXT_STRIDE+2*LAYER_22_NEXT_PADD)*LAYER_22_NUM_KER))*2
#WEIGHTS_LAYER_22 = int((LAYER_22_NUM_KER*(1+LAYER_22_BATCH_NORM)+LAYER_22_NUM_KER*LAYER_22_KER_SIZE*LAYER_22_KER_SIZE*LAYER_22_C))

#Layer23 (conv)
LAYER_23_W = int(LAYER_22_W)
LAYER_23_C = int(LAYER_22_NUM_KER)
LAYER_23_NUM_KER = int(255)
LAYER_23_KER_SIZE = int(1)
LAYER_23_PAD = int(0)
LAYER_23_BATCH_NORM = int(0)
LAYER_23_NEXT_PADD = int(0)
LAYER_23_NEXT_STRIDE = int(0)
LAYER_23_IGNORE_PADD = int(0)
DATA_LAYER_23 = int(((LAYER_23_W+LAYER_23_NEXT_STRIDE+2*LAYER_23_NEXT_PADD)*(LAYER_23_W+LAYER_23_NEXT_STRIDE+2*LAYER_23_NEXT_PADD)*LAYER_23_NUM_KER))*2
#WEIGHTS_LAYER_23 = int((LAYER_23_NUM_KER*(1+LAYER_23_BATCH_NORM)+LAYER_23_NUM_KER*LAYER_23_KER_SIZE*LAYER_23_KER_SIZE*LAYER_23_C))

#Layer 24 (yolo)
LAYER_24_W = int(LAYER_23_W)
DATA_LAYER_24 = int((LAYER_23_W*LAYER_23_W*255))*2

#Total
#TOTAL_WEIGTHS = int((WEIGHTS_LAYER_1 + WEIGHTS_LAYER_3 + WEIGHTS_LAYER_5 + WEIGHTS_LAYER_7 + WEIGHTS_LAYER_9 + WEIGHTS_LAYER_11 + WEIGHTS_LAYER_13 + WEIGHTS_LAYER_14 + WEIGHTS_LAYER_15 + WEIGHTS_LAYER_16 + WEIGHTS_LAYER_19 + WEIGHTS_LAYER_22 + WEIGHTS_LAYER_23))
TOTAL_DATA = int((IMAGE_INPUT + NETWORK_INPUT + DATA_LAYER_1 + DATA_LAYER_2 + DATA_LAYER_3 + DATA_LAYER_4 + DATA_LAYER_5 + DATA_LAYER_6 + DATA_LAYER_7 + DATA_LAYER_8 + DATA_LAYER_9 + DATA_LAYER_10 + DATA_LAYER_11 + DATA_LAYER_12 + DATA_LAYER_13 + DATA_LAYER_14 + DATA_LAYER_15 + DATA_LAYER_16 + DATA_LAYER_17 + DATA_LAYER_19 + DATA_LAYER_20 + DATA_LAYER_22 + DATA_LAYER_23 + DATA_LAYER_24))