#include <stdint.h>

//Input image
#define IMG_W 768
#define IMG_H 576
#define IMG_C 3
#define NEW_W 416
#define NEW_H ((IMG_H*NEW_W)/IMG_W)	//312
#define w_scale ((uint32_t)(((float)(IMG_W-1)/(NEW_W-1))*((uint32_t)1<<22))) // Q1.22
#define h_scale ((uint32_t)(((float)(IMG_H-1)/(NEW_H-1))*((uint32_t)1<<20))) // Q1.20
#define IMAGE_INPUT (IMG_W*IMG_H*IMG_C)
#define EXTRA_H ((NEW_W-NEW_H)/2)

//Input network
#define NTW_IN_W 416
#define NTW_IN_C 3
#define NTW_IN_NUM_KER 16
#define NTW_IN_KER_SIZE 3
#define NTW_IN_PAD 1
#define NTW_IN_BATCH_NORM 1
#define NTW_IN_NEXT_PADD 0
#define NTW_IN_NEXT_STRIDE 0
#define NTW_IN_IGNORE_PADD 0
#define NETWORK_INPUT ((NTW_IN_W+2*NTW_IN_PAD)*(NEW_H+4)*NTW_IN_C)

//Layer1 (conv)
#define DATA_LAYER_1 ((NTW_IN_W+NTW_IN_NEXT_STRIDE+2*NTW_IN_NEXT_PADD)*(NEW_H+4)*NTW_IN_NUM_KER)
#define WEIGHTS_LAYER_1 (NTW_IN_NUM_KER*(1+NTW_IN_BATCH_NORM)+NTW_IN_NUM_KER*NTW_IN_KER_SIZE*NTW_IN_KER_SIZE*NTW_IN_C)

//Layer2 (maxpool)
#define LAYER_2_W NTW_IN_W
#define LAYER_2_NUM_KER NTW_IN_NUM_KER
#define LAYER_2_DOWNSAMPLE 1
#define LAYER_2_IGNORE_PADD 0
#define DATA_LAYER_2 ((LAYER_2_W/(1+LAYER_2_DOWNSAMPLE)+2)*162*LAYER_2_NUM_KER)

//Layer3 (conv)
#define LAYER_3_W (LAYER_2_W/2)
#define LAYER_3_C LAYER_2_NUM_KER
#define LAYER_3_NUM_KER LAYER_3_C*2
#define LAYER_3_KER_SIZE 3
#define LAYER_3_PAD 1
#define LAYER_3_BATCH_NORM 1
#define LAYER_3_NEXT_PADD 0
#define LAYER_3_NEXT_STRIDE 0
#define LAYER_3_IGNORE_PADD 0
#define DATA_LAYER_3 ((LAYER_3_W+LAYER_3_NEXT_STRIDE+2*LAYER_3_NEXT_PADD)*(LAYER_3_W+LAYER_3_NEXT_STRIDE+2*LAYER_3_NEXT_PADD)*LAYER_3_NUM_KER)
#define WEIGHTS_LAYER_3 (LAYER_3_NUM_KER*(1+LAYER_3_BATCH_NORM)+LAYER_3_NUM_KER*LAYER_3_KER_SIZE*LAYER_3_KER_SIZE*LAYER_3_C)

//Layer4 (maxpool)
#define LAYER_4_W LAYER_3_W
#define LAYER_4_NUM_KER LAYER_3_NUM_KER
#define LAYER_4_DOWNSAMPLE 1
#define LAYER_4_IGNORE_PADD 0
#define DATA_LAYER_4 ((LAYER_3_W/(1+LAYER_4_DOWNSAMPLE)+2)*(LAYER_3_W/(1+LAYER_4_DOWNSAMPLE)+2)*LAYER_3_NUM_KER)

//Layer5 (conv)
#define LAYER_5_W (LAYER_4_W/2)
#define LAYER_5_C LAYER_4_NUM_KER
#define LAYER_5_NUM_KER LAYER_5_C*2
#define LAYER_5_KER_SIZE 3
#define LAYER_5_PAD 1
#define LAYER_5_BATCH_NORM 1
#define LAYER_5_NEXT_PADD 0
#define LAYER_5_NEXT_STRIDE 0
#define LAYER_5_IGNORE_PADD 0
#define DATA_LAYER_5 ((LAYER_5_W+LAYER_5_NEXT_STRIDE+2*LAYER_5_NEXT_PADD)*(LAYER_5_W+LAYER_5_NEXT_STRIDE+2*LAYER_5_NEXT_PADD)*LAYER_5_NUM_KER)
#define WEIGHTS_LAYER_5 (LAYER_5_NUM_KER*(1+LAYER_5_BATCH_NORM)+LAYER_5_NUM_KER*LAYER_5_KER_SIZE*LAYER_5_KER_SIZE*LAYER_5_C)

//Layer6 (maxpool)
#define LAYER_6_W LAYER_5_W
#define LAYER_6_NUM_KER LAYER_5_NUM_KER
#define LAYER_6_DOWNSAMPLE 1
#define LAYER_6_IGNORE_PADD 0
#define DATA_LAYER_6 ((LAYER_5_W/2+(1+LAYER_6_DOWNSAMPLE))*(LAYER_5_W/(1+LAYER_6_DOWNSAMPLE)+2)*LAYER_5_NUM_KER)

//Layer7 (conv)
#define LAYER_7_W (LAYER_6_W/2)
#define LAYER_7_C LAYER_6_NUM_KER
#define LAYER_7_NUM_KER LAYER_7_C*2
#define LAYER_7_KER_SIZE 3
#define LAYER_7_PAD 1
#define LAYER_7_BATCH_NORM 1
#define LAYER_7_NEXT_PADD 0
#define LAYER_7_NEXT_STRIDE 0
#define LAYER_7_IGNORE_PADD 0
#define DATA_LAYER_7 ((LAYER_7_W+LAYER_7_NEXT_STRIDE+2*LAYER_7_NEXT_PADD)*(LAYER_7_W+LAYER_7_NEXT_STRIDE+2*LAYER_7_NEXT_PADD)*LAYER_7_NUM_KER)
#define WEIGHTS_LAYER_7 (LAYER_7_NUM_KER*(1+LAYER_7_BATCH_NORM)+LAYER_7_NUM_KER*LAYER_7_KER_SIZE*LAYER_7_KER_SIZE*LAYER_7_C)

//Layer8 (maxpool)
#define LAYER_8_W LAYER_7_W
#define LAYER_8_NUM_KER LAYER_7_NUM_KER
#define LAYER_8_DOWNSAMPLE 1
#define LAYER_8_IGNORE_PADD 0
#define DATA_LAYER_8 ((LAYER_7_W/(1+LAYER_8_DOWNSAMPLE)+2)*(LAYER_7_W/(1+LAYER_8_DOWNSAMPLE)+2)*LAYER_7_NUM_KER)

//Layer9 (conv)
#define LAYER_9_W (LAYER_8_W/2)
#define LAYER_9_C LAYER_8_NUM_KER
#define LAYER_9_NUM_KER LAYER_9_C*2
#define LAYER_9_KER_SIZE 3
#define LAYER_9_PAD 1
#define LAYER_9_BATCH_NORM 1
#define LAYER_9_NEXT_PADD 1
#define LAYER_9_NEXT_STRIDE 0
#define LAYER_9_IGNORE_PADD 0
#define DATA_LAYER_9 ((LAYER_9_W+LAYER_9_NEXT_STRIDE+2*LAYER_9_NEXT_PADD)*(LAYER_9_W+LAYER_9_NEXT_STRIDE+2*LAYER_9_NEXT_PADD)*LAYER_9_NUM_KER)
#define WEIGHTS_LAYER_9 (LAYER_9_NUM_KER*(1+LAYER_9_BATCH_NORM)+LAYER_9_NUM_KER*LAYER_9_KER_SIZE*LAYER_9_KER_SIZE*LAYER_9_C)

//Layer10 (maxpool)
#define LAYER_10_W LAYER_9_W
#define LAYER_10_NUM_KER LAYER_9_NUM_KER
#define LAYER_10_DOWNSAMPLE 1
#define LAYER_10_IGNORE_PADD 1
#define DATA_LAYER_10 ((LAYER_9_W/(1+LAYER_10_DOWNSAMPLE)+2)*(LAYER_9_W/(1+LAYER_10_DOWNSAMPLE)+2)*LAYER_9_NUM_KER)

//Layer11 (conv)
#define LAYER_11_W (LAYER_10_W/2)
#define LAYER_11_C LAYER_10_NUM_KER
#define LAYER_11_NUM_KER LAYER_11_C*2
#define LAYER_11_KER_SIZE 3
#define LAYER_11_PAD 1
#define LAYER_11_BATCH_NORM 1
#define LAYER_11_NEXT_PADD 0
#define LAYER_11_NEXT_STRIDE 1
#define LAYER_11_IGNORE_PADD 0
#define DATA_LAYER_11 ((LAYER_11_W+LAYER_11_NEXT_STRIDE+2*LAYER_11_NEXT_PADD)*(LAYER_11_W+LAYER_11_NEXT_STRIDE+2*LAYER_11_NEXT_PADD)*LAYER_11_NUM_KER)
#define WEIGHTS_LAYER_11 (LAYER_11_NUM_KER*(1+LAYER_11_BATCH_NORM)+LAYER_11_NUM_KER*LAYER_11_KER_SIZE*LAYER_11_KER_SIZE*LAYER_11_C)

//Layer12 (maxpool)
#define LAYER_12_W LAYER_11_W
#define LAYER_12_NUM_KER LAYER_11_NUM_KER
#define LAYER_12_DOWNSAMPLE 0
#define LAYER_12_IGNORE_PADD 0
#define DATA_LAYER_12 ((LAYER_11_W/(1+LAYER_12_DOWNSAMPLE)+2)*(LAYER_11_W/(1+LAYER_12_DOWNSAMPLE)+2)*LAYER_11_NUM_KER)

//Layer13 (conv)
#define LAYER_13_W LAYER_12_W
#define LAYER_13_C LAYER_12_NUM_KER
#define LAYER_13_NUM_KER LAYER_13_C*2
#define LAYER_13_KER_SIZE 3
#define LAYER_13_PAD 1
#define LAYER_13_BATCH_NORM 1
#define LAYER_13_NEXT_PADD 0
#define LAYER_13_NEXT_STRIDE 0
#define LAYER_13_IGNORE_PADD 0
#define DATA_LAYER_13 ((LAYER_13_W+LAYER_13_NEXT_STRIDE+2*LAYER_13_NEXT_PADD)*(LAYER_13_W+LAYER_13_NEXT_STRIDE+2*LAYER_13_NEXT_PADD)*LAYER_13_NUM_KER)
#define WEIGHTS_LAYER_13 (LAYER_13_NUM_KER*(1+LAYER_13_BATCH_NORM)+LAYER_13_NUM_KER*LAYER_13_KER_SIZE*LAYER_13_KER_SIZE*LAYER_13_C)

//Layer14 (conv)
#define LAYER_14_W LAYER_13_W
#define LAYER_14_C LAYER_13_NUM_KER
#define LAYER_14_NUM_KER (LAYER_14_C/4)
#define LAYER_14_KER_SIZE 1
#define LAYER_14_PAD 0
#define LAYER_14_BATCH_NORM 1
#define LAYER_14_NEXT_PADD 1
#define LAYER_14_NEXT_STRIDE 0
#define LAYER_14_IGNORE_PADD 0
#define DATA_LAYER_14 ((LAYER_14_W+LAYER_14_NEXT_STRIDE+2*LAYER_14_NEXT_PADD)*(LAYER_14_W+LAYER_14_NEXT_STRIDE+2*LAYER_14_NEXT_PADD)*LAYER_14_NUM_KER)
#define WEIGHTS_LAYER_14 (LAYER_14_NUM_KER*(1+LAYER_14_BATCH_NORM)+LAYER_14_NUM_KER*LAYER_14_KER_SIZE*LAYER_14_KER_SIZE*LAYER_14_C)

//Layer15 (conv)
#define LAYER_15_W LAYER_14_W
#define LAYER_15_C LAYER_14_NUM_KER
#define LAYER_15_NUM_KER (LAYER_15_C*2)
#define LAYER_15_KER_SIZE 3
#define LAYER_15_PAD 1
#define LAYER_15_BATCH_NORM 1
#define LAYER_15_NEXT_PADD 0
#define LAYER_15_NEXT_STRIDE 0
#define LAYER_15_IGNORE_PADD 0
#define DATA_LAYER_15 ((LAYER_15_W+LAYER_15_NEXT_STRIDE+2*LAYER_15_NEXT_PADD)*(LAYER_15_W+LAYER_15_NEXT_STRIDE+2*LAYER_15_NEXT_PADD)*LAYER_15_NUM_KER)
#define WEIGHTS_LAYER_15 (LAYER_15_NUM_KER*(1+LAYER_15_BATCH_NORM)+LAYER_15_NUM_KER*LAYER_15_KER_SIZE*LAYER_15_KER_SIZE*LAYER_15_C)

//Layer16 (conv)
#define LAYER_16_W LAYER_15_W
#define LAYER_16_C LAYER_15_NUM_KER
#define LAYER_16_NUM_KER 255
#define LAYER_16_KER_SIZE 1
#define LAYER_16_PAD 0
#define LAYER_16_BATCH_NORM 0
#define LAYER_16_NEXT_PADD 0
#define LAYER_16_NEXT_STRIDE 0
#define LAYER_16_IGNORE_PADD 0
#define DATA_LAYER_16 ((LAYER_16_W+LAYER_16_NEXT_STRIDE+2*LAYER_16_NEXT_PADD)*(LAYER_16_W+LAYER_16_NEXT_STRIDE+2*LAYER_16_NEXT_PADD)*LAYER_16_NUM_KER)
#define WEIGHTS_LAYER_16 (LAYER_16_NUM_KER*(1+LAYER_16_BATCH_NORM)+LAYER_16_NUM_KER*LAYER_16_KER_SIZE*LAYER_16_KER_SIZE*LAYER_16_C)

//Layer 17 (yolo)
#define LAYER_17_W LAYER_16_W
#define DATA_LAYER_17 (LAYER_17_W*LAYER_17_W*255)

//Layer19 (conv)
#define LAYER_19_W LAYER_14_W
#define LAYER_19_C LAYER_14_NUM_KER
#define LAYER_19_NUM_KER (LAYER_19_C/2)
#define LAYER_19_KER_SIZE 1
#define LAYER_19_PAD 1
#define LAYER_19_BATCH_NORM 1
#define LAYER_19_NEXT_PADD 0
#define LAYER_19_NEXT_STRIDE 0
#define LAYER_19_IGNORE_PADD 1
#define DATA_LAYER_19 ((LAYER_19_W+LAYER_19_NEXT_STRIDE+2*LAYER_19_NEXT_PADD)*(LAYER_19_W+LAYER_19_NEXT_STRIDE+2*LAYER_19_NEXT_PADD)*LAYER_19_NUM_KER)
#define WEIGHTS_LAYER_19 (LAYER_19_NUM_KER*(1+LAYER_19_BATCH_NORM)+LAYER_19_NUM_KER*LAYER_19_KER_SIZE*LAYER_19_KER_SIZE*LAYER_19_C)

//Layer20 (upsample)
#define LAYER_20_W LAYER_19_W
#define LAYER_20_NUM_KER LAYER_19_NUM_KER
#define DATA_LAYER_20 ((LAYER_20_W*2+2)*(LAYER_20_W*2+2)*LAYER_20_NUM_KER)

//Layer22 (conv)
#define LAYER_22_W LAYER_20_W*2
#define LAYER_22_C (LAYER_20_NUM_KER + LAYER_9_NUM_KER)
#define LAYER_22_NUM_KER LAYER_9_NUM_KER
#define LAYER_22_KER_SIZE 3
#define LAYER_22_PAD 1
#define LAYER_22_BATCH_NORM 1
#define LAYER_22_NEXT_PADD 0
#define LAYER_22_NEXT_STRIDE 0
#define LAYER_22_IGNORE_PADD 0
#define DATA_LAYER_22 ((LAYER_22_W+LAYER_22_NEXT_STRIDE+2*LAYER_22_NEXT_PADD)*(LAYER_22_W+LAYER_22_NEXT_STRIDE+2*LAYER_22_NEXT_PADD)*LAYER_22_NUM_KER)
#define WEIGHTS_LAYER_22 (LAYER_22_NUM_KER*(1+LAYER_22_BATCH_NORM)+LAYER_22_NUM_KER*LAYER_22_KER_SIZE*LAYER_22_KER_SIZE*LAYER_22_C)

//Layer23 (conv)
#define LAYER_23_W LAYER_22_W
#define LAYER_23_C LAYER_22_NUM_KER
#define LAYER_23_NUM_KER 255
#define LAYER_23_KER_SIZE 1
#define LAYER_23_PAD 0
#define LAYER_23_BATCH_NORM 0
#define LAYER_23_NEXT_PADD 0
#define LAYER_23_NEXT_STRIDE 0
#define LAYER_23_IGNORE_PADD 0
#define DATA_LAYER_23 ((LAYER_23_W+LAYER_23_NEXT_STRIDE+2*LAYER_23_NEXT_PADD)*(LAYER_23_W+LAYER_23_NEXT_STRIDE+2*LAYER_23_NEXT_PADD)*LAYER_23_NUM_KER)
#define WEIGHTS_LAYER_23 (LAYER_23_NUM_KER*(1+LAYER_23_BATCH_NORM)+LAYER_23_NUM_KER*LAYER_23_KER_SIZE*LAYER_23_KER_SIZE*LAYER_23_C)

//Layer 24 (yolo)
#define LAYER_24_W LAYER_23_W
#define DATA_LAYER_24 (LAYER_23_W*LAYER_23_W*255)

//Total
#define TOTAL_WEIGTHS (WEIGHTS_LAYER_1 + WEIGHTS_LAYER_3 + WEIGHTS_LAYER_5 + WEIGHTS_LAYER_7 + WEIGHTS_LAYER_9 + WEIGHTS_LAYER_11 + WEIGHTS_LAYER_13 + WEIGHTS_LAYER_14 + WEIGHTS_LAYER_15 + WEIGHTS_LAYER_16 + WEIGHTS_LAYER_19 + WEIGHTS_LAYER_22 + WEIGHTS_LAYER_23)
#define TOTAL_DATA (IMAGE_INPUT + NETWORK_INPUT + DATA_LAYER_1 + DATA_LAYER_2 + DATA_LAYER_3 + DATA_LAYER_4 + DATA_LAYER_5 + DATA_LAYER_6 + DATA_LAYER_7 + DATA_LAYER_8 + DATA_LAYER_9 + DATA_LAYER_10 + DATA_LAYER_11 + DATA_LAYER_12 + DATA_LAYER_13 + DATA_LAYER_14 + DATA_LAYER_15 + DATA_LAYER_16 + DATA_LAYER_17 + DATA_LAYER_19 + DATA_LAYER_20 + DATA_LAYER_22 + DATA_LAYER_23 + DATA_LAYER_24)

