//Input image
#define IMG_W 768
#define IMG_H 576
#define IMG_C 3
#define IMAGE_INPUT (IMG_W*IMG_H*IMG_C)

//Resized image
#define YOLO_INPUT 416
#define NEW_W YOLO_INPUT
#define NEW_H ((IMG_H*NEW_W)/IMG_W)
#define EXTRA_W 0
#define EXTRA_H ((NEW_W-NEW_H)/2)

//Input network
#define NETWORK_INPUT ((YOLO_INPUT+2)*(YOLO_INPUT+2)*IMG_C)

//Layer1,2 (conv + maxpool)
#define LAYER_1_MAXPOOL 1
#define LAYER_1_NUM_KER 16
#define LAYER_1_KER_SIZE 3
#define WEIGHTS_LAYER_1 (LAYER_1_NUM_KER+LAYER_1_NUM_KER*LAYER_1_KER_SIZE*LAYER_1_KER_SIZE*IMG_C)
#define LAYER_2_W 210
#define DATA_LAYER_2 (LAYER_2_W*LAYER_2_W*LAYER_1_NUM_KER)

//Layer3,4 (conv + maxpool)
#define LAYER_3_MAXPOOL 1
#define LAYER_3_W 208
#define LAYER_3_NUM_KER 32
#define LAYER_3_KER_SIZE 3
#define WEIGHTS_LAYER_3 (LAYER_3_NUM_KER+LAYER_3_NUM_KER*LAYER_3_KER_SIZE*LAYER_3_KER_SIZE*LAYER_1_NUM_KER)
#define LAYER_4_W 106
#define DATA_LAYER_4 (LAYER_4_W*LAYER_4_W*LAYER_3_NUM_KER)

//Layer5,6 (conv + maxpool)
#define LAYER_5_MAXPOOL 1
#define LAYER_5_W 104
#define LAYER_5_NUM_KER 64
#define LAYER_5_KER_SIZE 3
#define WEIGHTS_LAYER_5 (LAYER_5_NUM_KER+LAYER_5_NUM_KER*LAYER_5_KER_SIZE*LAYER_5_KER_SIZE*LAYER_3_NUM_KER)
#define LAYER_6_W 54
#define DATA_LAYER_6 (LAYER_6_W*LAYER_6_W*LAYER_5_NUM_KER)

//Layer7,8 (conv + maxpool)
#define LAYER_7_MAXPOOL 1
#define LAYER_7_W 52
#define LAYER_7_NUM_KER 128
#define LAYER_7_KER_SIZE 3
#define WEIGHTS_LAYER_7 (LAYER_7_NUM_KER+LAYER_7_NUM_KER*LAYER_7_KER_SIZE*LAYER_7_KER_SIZE*LAYER_5_NUM_KER)
#define LAYER_8_W 28
#define DATA_LAYER_8 (LAYER_8_W*LAYER_8_W*LAYER_7_NUM_KER)

//Layer9 (conv)
#define LAYER_9_MAXPOOL 0
#define LAYER_9_W 26
#define LAYER_9_NUM_KER 256
#define LAYER_9_KER_SIZE 3
#define WEIGHTS_LAYER_9 (LAYER_9_NUM_KER+LAYER_9_NUM_KER*LAYER_9_KER_SIZE*LAYER_9_KER_SIZE*LAYER_7_NUM_KER)
#define DATA_LAYER_9 ((LAYER_9_W+2)*(LAYER_9_W+2)*LAYER_9_NUM_KER)

//Total
#define TOTAL_WEIGHTS (WEIGHTS_LAYER_1 + WEIGHTS_LAYER_3 + WEIGHTS_LAYER_5 + WEIGHTS_LAYER_7 + WEIGHTS_LAYER_9)
