//Layer1,2 (conv + maxpool)
#define LAYER_1_INPADD 1
#define LAYER_1_IGNOREPAD 0
#define LAYER_1_STRIDE 0
#define LAYER_1_OUTPADD 1
#define LAYER_1_MAXPOOL 1
#define LAYER_1_W 416
#define LAYER_1_NUM_KER 16
#define LAYER_1_KER_SIZE 3
#define LAYER_1_C 3
#define LAYER_1_P_OFF 10
#define LAYER_1_W_OFF 5
#define DATA_LAYER_1 ((LAYER_1_W+2)*((LAYER_1_W+2)*LAYER_1_C+LAYER_1_P_OFF))
#define WEIGHTS_LAYER_1 (LAYER_1_NUM_KER+LAYER_1_NUM_KER*(LAYER_1_KER_SIZE*LAYER_1_KER_SIZE*LAYER_1_C+LAYER_1_W_OFF))
#define LAYER_2_W 210
#define DATA_LAYER_2 (LAYER_2_W*LAYER_2_W*LAYER_1_NUM_KER)

//Total
#define TOTAL_WEIGHTS (WEIGHTS_LAYER_1)

